apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.webapp.name }}-{{ randAlphaNum 5 | lower }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.webapp.name }}
    group: {{ .Values.webapp.group }}
spec:
  template:
    metadata:
      labels:
        app: {{ .Values.webapp.name }}
    spec:
      restartPolicy: Never
      volumes:
        - name: {{ .Values.webapp.volume1.name }}
          nfs:
            server: {{ .Values.webapp.volume1.server }}
            path: {{ .Values.webapp.volume1.path }}
            readOnly: {{ .Values.webapp.volume1.readOnly }}
        - name: {{ .Values.webapp.volume2.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.webapp.volume2.name }}
      runtimeClassName: nvidia
      securityContext:
        fsGroup: 1000
      containers:
      - name: {{ .Values.webapp.name }}
        image: {{ .Values.webapp.container.image }}
        imagePullPolicy: {{ .Values.webapp.imagePullPolicy }}
        command: ["/bin/bash", "-c"]
        args:
          - |
            ls
            #python applications/gfs_init.py
            #conda run -n credit python -c "import torch; print(\"CUDA available?\", torch.cuda.is_available())"
            #nvidia-smi &&
            #bash /usr/local/bin/gpu-test &&
            #ls /usr/local/bin/gpu-test &&
            #echo "foo5" &&
            
        #command: ["/bin/bash", "-c"]
        #args:
        #  - |
        #    echo foo;
#        command: ["/bin/bash", "-c"]
#        args:
#          - |
#            echo "Starting job...";
#            export TZ=MST;
#            RESULT=$(date);
#            echo "The current date is: $RESULT";
        #command: ["/bin/bash", "-c"]
        #args:
        #  - |
        #    ls;
        #    ls /usr/local/bin/gpu-test;
        #    /usr/local/bin/gpu-test;
        #args: ["-c", "/usr/local/bin/gpu-test"]
        tty: true
        resources:
          limits:
            memory: {{ .Values.webapp.container.limits.memory }}
            cpu: {{ .Values.webapp.container.limits.cpu }}
            nvidia.com/gpu: "1"
          requests:
            memory: {{ .Values.webapp.container.requests.memory }}
            cpu: {{ .Values.webapp.container.requests.cpu }}
            nvidia.com/gpu: "1"
        volumeMounts:
        - mountPath: /glade/campaign
          name: {{ .Values.webapp.volume1.name }}
        - mountPath: /output
          name: {{ .Values.webapp.volume2.name }}
