apiVersion: batch/v1
kind: Pod
metadata:
  name: nginx-hello
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.webapp.name }}
    group: {{ .Values.webapp.group }}
spec:
  containers:
  - image: docker.io/ncging/argo-flask-demo:2025-06-24.16.33
    name: pod
    command:
    - echo
    - Hello
